"""
Compare FCI performance when hiding root-like vs intermediate confounders.

This script mirrors the Fig. 4/Fig. 5 comparison in the manuscript:

* standard/root: hide the first topologically sorted confounder
* intermediate: hide later topologically sorted confounders

It writes a CSV summary and a boxplot of normalized SHD.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from causallearn.search.ConstraintBased.FCI import fci

from causalspyne import gen_partially_observed
from causalspyne.ancestral_shd import structural_hamming_distance


SCENARIOS = {
    "root": {
        "label": "Root / standard",
        "hidden": [0],
    },
    "intermediate": {
        "label": "Intermediate",
        "hidden": [0.7, 0.9],
    },
}


def _node_summary(dag, hidden_global_indices):
    binary_adj = (dag.mat_adjacency != 0).astype(int)
    summaries = []
    for ind in hidden_global_indices:
        parents = np.flatnonzero(binary_adj[ind, :]).tolist()
        children = np.flatnonzero(binary_adj[:, ind]).tolist()
        summaries.append(
            {
                "index": int(ind),
                "name": dag.list_node_names[ind],
                "num_parents": len(parents),
                "num_children": len(children),
                "is_root": len(parents) == 0,
            }
        )
    return summaries


def run_one(args, scenario_name, scenario, seed):
    run_dir = args.output_dir / scenario_name / f"seed_{seed}"
    run_dir.mkdir(parents=True, exist_ok=True)

    subview = gen_partially_observed(
        size_micro_node_dag=args.size_micro_node_dag,
        num_macro_nodes=args.num_macro_nodes,
        degree=args.degree,
        list_confounder2hide=scenario["hidden"],
        num_sample=args.samples,
        output_dir=run_dir,
        rng=seed,
        graphviz=args.graphviz,
        plot=args.plot_examples,
    )

    graph, _ = fci(
        subview.data,
        alpha=args.alpha,
        verbose=False,
        show_progress=not args.no_progress,
        node_names=subview.node_names,
    )

    hidden_global_indices = subview.list_global_inds_nodes2hide
    shd = structural_hamming_distance(
        true_dag=subview.dag.mat_adjacency,
        true_hidden_nodes=hidden_global_indices,
        prediction=graph.graph,
    )
    hidden_nodes = _node_summary(subview.dag, hidden_global_indices)

    return {
        "scenario": scenario_name,
        "scenario_label": scenario["label"],
        "seed": seed,
        "normalized_shd": shd,
        "num_observed": subview.data.shape[1],
        "num_hidden": len(hidden_global_indices),
        "hidden_global_indices": ";".join(str(node["index"]) for node in hidden_nodes),
        "hidden_node_names": ";".join(node["name"] for node in hidden_nodes),
        "hidden_parent_counts": ";".join(
            str(node["num_parents"]) for node in hidden_nodes
        ),
        "hidden_child_counts": ";".join(
            str(node["num_children"]) for node in hidden_nodes
        ),
        "all_hidden_are_roots": all(node["is_root"] for node in hidden_nodes),
    }


def plot_results(df, output_path):
    labels = [SCENARIOS[name]["label"] for name in SCENARIOS]
    values = [
        df.loc[df["scenario"] == name, "normalized_shd"].to_numpy()
        for name in SCENARIOS
    ]

    fig, ax = plt.subplots(figsize=(6, 4))
    ax.boxplot(values, tick_labels=labels)
    ax.scatter(
        np.concatenate(
            [np.full(len(group), idx + 1) for idx, group in enumerate(values)]
        ),
        np.concatenate(values),
        color="black",
        s=18,
        alpha=0.7,
        zorder=3,
    )
    ax.set_ylabel("Normalized SHD")
    ax.set_xlabel("Hidden confounder setting")
    ax.set_title("FCI sensitivity to hidden confounder position")
    fig.tight_layout()
    fig.savefig(output_path)
    plt.close(fig)


def parse_args():
    parser = argparse.ArgumentParser(
        description=(
            "Compare FCI on data generated by hiding root-like and "
            "intermediate confounders."
        )
    )
    parser.add_argument("--replicates", type=int, default=10)
    parser.add_argument("--seed-start", type=int, default=0)
    parser.add_argument("--samples", type=int, default=200)
    parser.add_argument("--size-micro-node-dag", type=int, default=3)
    parser.add_argument("--num-macro-nodes", type=int, default=3)
    parser.add_argument("--degree", type=float, default=2)
    parser.add_argument("--alpha", type=float, default=0.05)
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("output/fci_confounder_position"),
    )
    parser.add_argument(
        "--plot-examples",
        action="store_true",
        help="Also write DAG/ancestral/subDAG comparison figures for each run.",
    )
    parser.add_argument(
        "--graphviz",
        action="store_true",
        help="Use graphviz layouts for generated DAG comparison figures.",
    )
    parser.add_argument(
        "--no-progress",
        action="store_true",
        help="Disable causal-learn progress bars.",
    )
    return parser.parse_args()


def main():
    args = parse_args()
    args.output_dir.mkdir(parents=True, exist_ok=True)

    records = []
    seeds = range(args.seed_start, args.seed_start + args.replicates)
    for seed in seeds:
        for scenario_name, scenario in SCENARIOS.items():
            records.append(run_one(args, scenario_name, scenario, seed))

    df = pd.DataFrame.from_records(records)
    csv_path = args.output_dir / "fci_confounder_position_results.csv"
    pdf_path = args.output_dir / "fci_confounder_position_boxplot.pdf"
    df.to_csv(csv_path, index=False)
    plot_results(df, pdf_path)

    summary = df.groupby("scenario_label")["normalized_shd"].agg(
        ["count", "mean", "std", "min", "max"]
    )
    print(summary)
    print(f"\nWrote {csv_path}")
    print(f"Wrote {pdf_path}")


if __name__ == "__main__":
    main()
