name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Run tests and upload coverage
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install dependencies (including dev)
        run: uv sync --dev

      - name: Run tests and generate coverage XML
        run: |
          rm -f coverage.xml
          uv run pytest \
            --cov=causalspyne \
            --cov-report=xml:coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
          flags: unittests
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

  deploy:
    name: Deploy HTML coverage site
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install dependencies (including dev)
        run: uv sync --dev

      - name: Generate HTML coverage
        run: |
          rm -rf htmlcov
          uv run pytest \
            --cov=causalspyne \
            --cov-report=html:htmlcov

      - name: Generate coverage badge
        run: |
          python -m pip install genbadge[coverage]
          genbadge coverage -i - < coverage.xml > coverage-badge.svg

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: htmlcov
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}
