jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: causalspyne
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install dependencies (including dev)
        run: uv sync --dev

      - name: Run tests and generate coverage
        run: |
          rm -rf htmlcov coverage.xml
          uv run pytest \
            --cov=causalspyne \
            --cov-report=xml:coverage.xml \
            --cov-report=html:htmlcov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
          flags: unittests
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Generate coverage badge
        run: |
          python -m pip install genbadge[coverage]
          genbadge coverage -i - < coverage.xml > htmlcov/coverage-badge.svg

  deploy-preview:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    environment:
      name: preview
      url: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/uv-preview/
    defaults:
      run:
        working-directory: causalspyne
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Deploy Preview Coverage
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: htmlcov
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}
