name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - run: uv sync
      - run: |
          rm -rf htmlcov coverage.xml
          uv run pytest \
            --cov=causalspyne \
            --cov-report=xml:coverage.xml \
            --cov-report=html:htmlcov

      - uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
          flags: unittests
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

      - run: |
          python -m pip install genbadge[coverage]
          genbadge coverage -i - < coverage.xml > htmlcov/coverage-badge.svg

  deploy:
    name: Deploy HTML Coverage
    runs-on: ubuntu-latest
    needs: test
    if: always()                     # deploy on both push and PR
    environment:
      name: github-pages            # <- registers a deployment
      url: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/
    steps:
      - uses: actions/checkout@v4
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: htmlcov
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}
