name: CI

on:
  push:
    branches: master
  pull_request:
    branches: master
  workflow_dispatch:

jobs:
  test:
    name: Run tests and publish coverage
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync

      - name: Run tests and generate coverage
        run: |
          rm -rf zoutput htmlcov
          uv run pytest \
            --cov=causalspyne \
            --cov-report=xml:coverage.xml \
            --cov-report=html:htmlcov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          flags: unittests
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Generate coverage badge
        run: |
          python -m pip install genbadge[coverage]
          genbadge coverage -i - < coverage.xml > htmlcov/coverage-badge.svg

      - name: Deploy HTML coverage to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: htmlcov
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}
