name: CI

on:
  push:
    branches: master
  pull_request:
    branches: master
  workflow_dispatch:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov pytest-shell
        python setup.py install
    - name: Install Python Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --with dev
    - name: Generate coverage report
      run: rm -rf zoutput && poetry run pytest --cov=causalSpyne tests/ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        flags: unittests
        env_vars: OS,PYTHON
        fail_ci_if_error: true
      env:
        CODECOV_TOKEN: 02ecb3ac-b7ce-4ea4-90a2-961c3d1a1030
